---
apiVersion: v1
kind: Service
metadata:
  name: alerts-collector
  labels:
    app: alerts-collector
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: alerts-collector-main-tls
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 8443
    protocol: TCP
    targetPort: web
  selector:
    app: alerts-collector
---

